// list of 100 common flowers
List<String> flowerList = [
  "African Daisy",
  "African Violet",
  "Agapanthus",
  "Ageratum",
  "Alyssum",
  "Amaryllis",
  "Anemone",
  "Angel's Trumpet",
  "Anthurium",
  "Apple Blossom",
  "Arum Lily",
  "Asiatic Lily",
  "Aster",
  "Azalea",
  "Baby's Breath",
  "Bachelor's Button",
  "Begonia",
  "Bellflower",
  "Bird of Paradise",
  "Bleeding Heart",
  "Bougainvillea",
  "Bromeliad",
  "Buttercup",
  "Butterfly Bush",
  "Butterfly Orchid",
  "Calendula",
  "Calla Lily",
  "Camellia",
  "Carnation",
  "Cattleya Orchid",
  "Ceriman",
  "Cherry Blossom",
  "Chrysanthemum",
  "Clematis",
  "Columbine",
  "Coneflower",
  "Coral Bells",
  "Cosmos",
  "Crocus",
  "Cyclamen",
  "Daffodil",
  "Dahlia",
  "Daisy",
  "Delphinium",
  "Dianthus",
  "Dusty Miller",
  "English Daisy",
  "Evening Primrose",
  "Fern",
  "Freesia",
  "Fuchsia",
  "Gardenia",
  "Geranium",
  "Gladiolus",
  "Gloxinia",
  "Grape Hyacinth",
  "Heather",
  "Hibiscus",
  "Hollyhock",
  "Hyacinth",
  "Hydrangea",
  "Iris",
  "Jasmine",
  "Jonquil",
  "Jungle Orchid",
  "Kalanchoe",
  "Kangaroo Paw",
  "Lavender",
  "Lily",
  "Lily of the Valley",
  "Lily of the Nile",
  "Lilyturf",
  "Lisianthus",
  "Lotus",
  "Magnolia",
  "Marigold",
  "Mimosa",
  "Morning Glory",
  "Narcissus",
  "Nasturtium",
  "Orchid",
  "Oxalis",
  "Pansy",
  "Peony",
  "Petunia",
  "Phlox",
  "Pincushion Flower",
  "Poinsettia",
  "Primrose",
  "Purple Coneflower",
  "Queen Anne's Lace",
  "Ranunculus",
  "Rose",
  "Rosemary",
  "Snapdragon",
  "Snowdrop",
  "Spider Plant",
  "Statice",
  "Sunflower",
  "Sweet Pea",
];
