// list of 1000 common succulents
List<String> succulentList = [
  "Aloe Vera",
  "Burro's Tail",
  "Cactus",
  "Crown of Thorns",
  "Echeveria",
  "Fairy Duster",
  "Fairy Wings",
  "Fern",
  "Flaming Katy",
  "Gasteria",
  "Haworthia",
  "Hens and Chicks",
  "Hoya",
  "Jade Plant",
  "Kalanchoe",
  "Kalanchoe Blossfeldiana",
  "Kalanchoe Daigremontiana",
  "Kalanchoe Fedtschenkoi",
  "Kalanchoe Flapjacks",
  "Kalanchoe Glauca",
  "Kalanchoe Luciae",
  "Kalanchoe Marnieriana",
  "Kalanchoe Pumila",
  "Kalanchoe Thyrsiflora",
  "Kalanchoe Tubiflora",
  "Kalanchoe Tumidiflora",
  "Lithops",
  "Maiden Hair Fern",
  "Mistletoe Cactus",
  "Mother of Thousands",
  "Panda Plant",
  "Rabbit's Foot Fern",
  "Red Hot Poker",
  "Sedum",
  "Sedum Burrito",
  "Sedum Burrito 'Coral Carpet'",
  "Sedum Burrito 'Coral Reef'",
  "Trailing Jade",
  "Umbrella Plant",
  "Venus Flytrap",
  "Yucca",
  "Zebra Plant",
];